/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CredentialDefinitionCreate } from '../models';
import { CredentialDefinitionSummary } from '../models';
/**
 * CredentialDefinitionsApi - axios parameter creator
 * @export
 */
export const CredentialDefinitionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new credentialDefinition
         * @param {CredentialDefinitionCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        credentialDefinitionPost: async (body: CredentialDefinitionCreate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling credentialDefinitionPost.');
            }
            const localVarPath = `/credential-definitions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CredentialDefinitionsApi - functional programming interface
 * @export
 */
export const CredentialDefinitionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new credentialDefinition
         * @param {CredentialDefinitionCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async credentialDefinitionPost(body: CredentialDefinitionCreate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CredentialDefinitionSummary>> {
            const localVarAxiosArgs = await CredentialDefinitionsApiAxiosParamCreator(configuration).credentialDefinitionPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CredentialDefinitionsApi - factory interface
 * @export
 */
export const CredentialDefinitionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new credentialDefinition
         * @param {CredentialDefinitionCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        credentialDefinitionPost(body: CredentialDefinitionCreate, options?: any): AxiosPromise<CredentialDefinitionSummary> {
            return CredentialDefinitionsApiFp(configuration).credentialDefinitionPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CredentialDefinitionsApi - object-oriented interface
 * @export
 * @class CredentialDefinitionsApi
 * @extends {BaseAPI}
 */
export class CredentialDefinitionsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new credentialDefinition
     * @param {CredentialDefinitionCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialDefinitionsApi
     */
    public credentialDefinitionPost(body: CredentialDefinitionCreate, options?: any) {
        return CredentialDefinitionsApiFp(this.configuration).credentialDefinitionPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
