/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CredentialsVerifyBody } from '../models';
import { VerifiablePresentation } from '../models';
import { VerificationResult } from '../models';
/**
 * JSONLDVerificationApi - axios parameter creator
 * @export
 */
export const JSONLDVerificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {VerifiablePresentation} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verityCredential: async (body: VerifiablePresentation, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling verityCredential.');
            }
            const localVarPath = `/presentations/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CredentialsVerifyBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verityCredential1: async (body: CredentialsVerifyBody, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling verityCredential1.');
            }
            const localVarPath = `/credentials/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JSONLDVerificationApi - functional programming interface
 * @export
 */
export const JSONLDVerificationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {VerifiablePresentation} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verityCredential(body: VerifiablePresentation, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerificationResult>> {
            const localVarAxiosArgs = await JSONLDVerificationApiAxiosParamCreator(configuration).verityCredential(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {CredentialsVerifyBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verityCredential1(body: CredentialsVerifyBody, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerificationResult>> {
            const localVarAxiosArgs = await JSONLDVerificationApiAxiosParamCreator(configuration).verityCredential1(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * JSONLDVerificationApi - factory interface
 * @export
 */
export const JSONLDVerificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {VerifiablePresentation} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verityCredential(body: VerifiablePresentation, options?: any): AxiosPromise<VerificationResult> {
            return JSONLDVerificationApiFp(configuration).verityCredential(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CredentialsVerifyBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verityCredential1(body: CredentialsVerifyBody, options?: any): AxiosPromise<VerificationResult> {
            return JSONLDVerificationApiFp(configuration).verityCredential1(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JSONLDVerificationApi - object-oriented interface
 * @export
 * @class JSONLDVerificationApi
 * @extends {BaseAPI}
 */
export class JSONLDVerificationApi extends BaseAPI {
    /**
     * 
     * @param {VerifiablePresentation} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JSONLDVerificationApi
     */
    public verityCredential(body: VerifiablePresentation, options?: any) {
        return JSONLDVerificationApiFp(this.configuration).verityCredential(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {CredentialsVerifyBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JSONLDVerificationApi
     */
    public verityCredential1(body: CredentialsVerifyBody, options?: any) {
        return JSONLDVerificationApiFp(this.configuration).verityCredential1(body, options).then((request) => request(this.axios, this.basePath));
    }
}
