/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AuthRequestParam } from '../models';
import { AuthRequestResponse } from '../models';
/**
 * OpenIDConnectConnectApi - axios parameter creator
 * @export
 */
export const OpenIDConnectConnectApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new authenticate url
         * @param {AuthRequestParam} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        didAuthRequest: async (body: AuthRequestParam, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling didAuthRequest.');
            }
            const localVarPath = `/oidc/didauthrequest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Processes Auth Response
         * @param {string} clientId 
         * @param {string} [idToken] 
         * @param {string} [state] 
         * @param {string} [loginChallenge] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        didAuthResponse: async (clientId: string, idToken?: string, state?: string, loginChallenge?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientId' is not null or undefined
            if (clientId === null || clientId === undefined) {
                throw new RequiredError('clientId','Required parameter clientId was null or undefined when calling didAuthResponse.');
            }
            const localVarPath = `/oidc/didauthresponse/{clientId}`
                .replace(`{${"clientId"}}`, encodeURIComponent(String(clientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (idToken !== undefined) { 
                localVarFormParams.set('id_token', idToken as any);
            }

            if (state !== undefined) { 
                localVarFormParams.set('state', state as any);
            }

            if (loginChallenge !== undefined) { 
                localVarFormParams.set('login_challenge', loginChallenge as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Sends a credential
         * @param {any} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendCredential: async (body: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling sendCredential.');
            }
            const localVarPath = `/oidc/sendcredential`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenIDConnectConnectApi - functional programming interface
 * @export
 */
export const OpenIDConnectConnectApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new authenticate url
         * @param {AuthRequestParam} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async didAuthRequest(body: AuthRequestParam, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthRequestResponse>> {
            const localVarAxiosArgs = await OpenIDConnectConnectApiAxiosParamCreator(configuration).didAuthRequest(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Processes Auth Response
         * @param {string} clientId 
         * @param {string} [idToken] 
         * @param {string} [state] 
         * @param {string} [loginChallenge] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async didAuthResponse(clientId: string, idToken?: string, state?: string, loginChallenge?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await OpenIDConnectConnectApiAxiosParamCreator(configuration).didAuthResponse(clientId, idToken, state, loginChallenge, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Sends a credential
         * @param {any} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendCredential(body: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await OpenIDConnectConnectApiAxiosParamCreator(configuration).sendCredential(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OpenIDConnectConnectApi - factory interface
 * @export
 */
export const OpenIDConnectConnectApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new authenticate url
         * @param {AuthRequestParam} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        didAuthRequest(body: AuthRequestParam, options?: any): AxiosPromise<AuthRequestResponse> {
            return OpenIDConnectConnectApiFp(configuration).didAuthRequest(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Processes Auth Response
         * @param {string} clientId 
         * @param {string} [idToken] 
         * @param {string} [state] 
         * @param {string} [loginChallenge] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        didAuthResponse(clientId: string, idToken?: string, state?: string, loginChallenge?: string, options?: any): AxiosPromise<any> {
            return OpenIDConnectConnectApiFp(configuration).didAuthResponse(clientId, idToken, state, loginChallenge, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Sends a credential
         * @param {any} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendCredential(body: any, options?: any): AxiosPromise<any> {
            return OpenIDConnectConnectApiFp(configuration).sendCredential(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenIDConnectConnectApi - object-oriented interface
 * @export
 * @class OpenIDConnectConnectApi
 * @extends {BaseAPI}
 */
export class OpenIDConnectConnectApi extends BaseAPI {
    /**
     * 
     * @summary Create a new authenticate url
     * @param {AuthRequestParam} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenIDConnectConnectApi
     */
    public didAuthRequest(body: AuthRequestParam, options?: any) {
        return OpenIDConnectConnectApiFp(this.configuration).didAuthRequest(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Processes Auth Response
     * @param {string} clientId 
     * @param {string} [idToken] 
     * @param {string} [state] 
     * @param {string} [loginChallenge] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenIDConnectConnectApi
     */
    public didAuthResponse(clientId: string, idToken?: string, state?: string, loginChallenge?: string, options?: any) {
        return OpenIDConnectConnectApiFp(this.configuration).didAuthResponse(clientId, idToken, state, loginChallenge, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Sends a credential
     * @param {any} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenIDConnectConnectApi
     */
    public sendCredential(body: any, options?: any) {
        return OpenIDConnectConnectApiFp(this.configuration).sendCredential(body, options).then((request) => request(this.axios, this.basePath));
    }
}
