/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Verification } from '../models';
import { VerificationCreate } from '../models';
import { VerificationTemplate } from '../models';
import { VerificationTemplateCreate } from '../models';
/**
 * VerificationsApi - axios parameter creator
 * @export
 */
export const VerificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new Verification Template
         * @param {VerificationTemplateCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verificationTemplatesPost: async (body: VerificationTemplateCreate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling verificationTemplatesPost.');
            }
            const localVarPath = `/verification-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new Verification
         * @param {VerificationCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verificationsPost: async (body: VerificationCreate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling verificationsPost.');
            }
            const localVarPath = `/verifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VerificationsApi - functional programming interface
 * @export
 */
export const VerificationsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new Verification Template
         * @param {VerificationTemplateCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verificationTemplatesPost(body: VerificationTemplateCreate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerificationTemplate>> {
            const localVarAxiosArgs = await VerificationsApiAxiosParamCreator(configuration).verificationTemplatesPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a new Verification
         * @param {VerificationCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verificationsPost(body: VerificationCreate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Verification>> {
            const localVarAxiosArgs = await VerificationsApiAxiosParamCreator(configuration).verificationsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VerificationsApi - factory interface
 * @export
 */
export const VerificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new Verification Template
         * @param {VerificationTemplateCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verificationTemplatesPost(body: VerificationTemplateCreate, options?: any): AxiosPromise<VerificationTemplate> {
            return VerificationsApiFp(configuration).verificationTemplatesPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new Verification
         * @param {VerificationCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verificationsPost(body: VerificationCreate, options?: any): AxiosPromise<Verification> {
            return VerificationsApiFp(configuration).verificationsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VerificationsApi - object-oriented interface
 * @export
 * @class VerificationsApi
 * @extends {BaseAPI}
 */
export class VerificationsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new Verification Template
     * @param {VerificationTemplateCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VerificationsApi
     */
    public verificationTemplatesPost(body: VerificationTemplateCreate, options?: any) {
        return VerificationsApiFp(this.configuration).verificationTemplatesPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a new Verification
     * @param {VerificationCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VerificationsApi
     */
    public verificationsPost(body: VerificationCreate, options?: any) {
        return VerificationsApiFp(this.configuration).verificationsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
