version: "3.9"
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    ports:
      - "${WEBAPP_PORT}:3000"
  backend:
    build: ./backend
    ports:
      - "${CONTROLLER_PORT}:8080"
    environment:
      - ACAPYCLIENT_BASEPATH=http://aca-py:${ACA_PY_ADMIN_PORT}
  aca-py:
    image: rdlabbridge/aries-cloudagent:latest
    ports:
      - "${ACA_PY_ADMIN_PORT}:${ACA_PY_ADMIN_PORT}"
      - "${ACA_PY_DIDCOMM_PORT}:${ACA_PY_DIDCOMM_PORT}"
    command: [
      "start",
      "--admin",
      "0.0.0.0",
      "${ACA_PY_ADMIN_PORT}",
      "--admin-insecure-mode",
      "--inbound-transport",
      "http",
      "0.0.0.0",
      "${ACA_PY_DIDCOMM_PORT}",
      "--outbound-transport",
      "http",
      "--endpoint",
      "${ACAPY_ENDPOINT}",
      "--webhook-url",
      "http://backend:${CONTROLLER_PORT}/api/",
      "--label",
      "Bridge Agent",
      "--genesis-url",
      "https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis",
      "--seed",
      "${ACAPY_WALLET_SEED}",
      "--auto-ping-connection",
      "--auto-accept-requests",
      "--auto-respond-messages",
      "--auto-respond-credential-proposal",
      "--auto-respond-credential-offer",
      "--auto-respond-credential-request",
      "--auto-respond-presentation-proposal",
      "--auto-respond-presentation-request",
      "--auto-store-credential",
      "--auto-verify-presentation"
    ]