/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthResponseCallback
 */
export interface AuthResponseCallback {
    /**
     * 
     * @type {string}
     * @memberof AuthResponseCallback
     */
    idToken: any;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseCallback
     */
    state: any;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseCallback
     */
    loginChallenge: any;
}
