/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConnectionInvitationContent
 */
export interface ConnectionInvitationContent {
    /**
     * The connection's invitation id
     * @type {string}
     * @memberof ConnectionInvitationContent
     */
    invitationId: any;
    /**
     * The connection's service endpoint
     * @type {string}
     * @memberof ConnectionInvitationContent
     */
    serviceEndpoint: any;
    /**
     * The list of recipient's keys
     * @type {Array&lt;string&gt;}
     * @memberof ConnectionInvitationContent
     */
    recipientKeys: any;
    /**
     * The connection's label
     * @type {string}
     * @memberof ConnectionInvitationContent
     */
    label?: any;
}
