/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CredentialCreate
 */
export interface CredentialCreate {
    /**
     * A connection ID
     * @type {string}
     * @memberof CredentialCreate
     */
    connectionId?: any;
    /**
     * A schema ID
     * @type {string}
     * @memberof CredentialCreate
     */
    schemaId: any;
    /**
     * A credential definition ID
     * @type {string}
     * @memberof CredentialCreate
     */
    credentialDefinitionId: any;
    /**
     * A human readable comment
     * @type {string}
     * @memberof CredentialCreate
     */
    comment?: any;
    /**
     * A list of credential attributes
     * @type {Array&lt;CredentialAttribute&gt;}
     * @memberof CredentialCreate
     */
    attributes: any;
}
