/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CredentialDefinitionCreate
 */
export interface CredentialDefinitionCreate {
    /**
     * Schema identifier
     * @type {string}
     * @memberof CredentialDefinitionCreate
     */
    schemaId: any;
    /**
     * Credential definition identifier tag
     * @type {string}
     * @memberof CredentialDefinitionCreate
     */
    tag: any;
    /**
     * Revocation supported flag
     * @type {boolean}
     * @memberof CredentialDefinitionCreate
     */
    supportRevocation: any;
}
