/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CredentialIssuance
 */
export interface CredentialIssuance {
    /**
     * A credential issuance ID
     * @type {string}
     * @memberof CredentialIssuance
     */
    issuanceId: any;
    /**
     * Optional error message
     * @type {string}
     * @memberof CredentialIssuance
     */
    errorMessage?: any;
    /**
     * State of the credential transaction
     * @type {string}
     * @memberof CredentialIssuance
     */
    state: any;
    /**
     * 
     * @type {Date}
     * @memberof CredentialIssuance
     */
    updatedAt?: any;
    /**
     * 
     * @type {Credential}
     * @memberof CredentialIssuance
     */
    credential: any;
}
