/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A JSON-LD Linked Data proof.
 * @export
 * @interface LinkedDataProof
 */
export interface LinkedDataProof {
    /**
     * Linked Data Signature Suite used to produce proof.
     * @type {string}
     * @memberof LinkedDataProof
     */
    type: any;
    /**
     * Date the proof was created.
     * @type {string}
     * @memberof LinkedDataProof
     */
    created: any;
    /**
     * Verification Method used to verify proof.
     * @type {string}
     * @memberof LinkedDataProof
     */
    verificationMethod: any;
    /**
     * The purpose of the proof to be used with verificationMethod.
     * @type {string}
     * @memberof LinkedDataProof
     */
    proofPurpose: any;
    /**
     * Detached JSON Web Signature
     * @type {string}
     * @memberof LinkedDataProof
     */
    jws: any;
    /**
     * 
     * @type {string}
     * @memberof LinkedDataProof
     */
    cades?: any;
}
