/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The requested predicates
 * @export
 * @interface RequestedPredicate
 */
export interface RequestedPredicate {
    /**
     * A predicate name
     * @type {string}
     * @memberof RequestedPredicate
     */
    name: any;
    /**
     * A predicate type
     * @type {string}
     * @memberof RequestedPredicate
     */
    predicateType: RequestedPredicatePredicateTypeEnum;
    /**
     * A predicate value
     * @type {number}
     * @memberof RequestedPredicate
     */
    predicateValue: any;
    /**
     * A list of predicate restrictions
     * @type {Array&lt;Restriction&gt;}
     * @memberof RequestedPredicate
     */
    restrictions: any;
}

/**
    * @export
    * @enum {string}
    */
export enum RequestedPredicatePredicateTypeEnum {
    LESSTHAN = 'LESS_THAN',
    LESSTHANOREQUALTO = 'LESS_THAN_OR_EQUAL_TO',
    GREATERTHANOREQUALTO = 'GREATER_THAN_OR_EQUAL_TO',
    GREATERTHAN = 'GREATER_THAN'
}

