/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The requested attributes
 * @export
 * @interface RequestedAttribute
 */
export interface RequestedAttribute {
    /**
     * List of attribute names
     * @type {Array&lt;string&gt;}
     * @memberof RequestedAttribute
     */
    names: any;
    /**
     * The attribute restrictions. At least one restriction should be valid in order for the verification to be successful. (Not considering predicates, revocation requirements...)
     * @type {Array&lt;Restriction&gt;}
     * @memberof RequestedAttribute
     */
    restrictions: any;
}
