/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A list of predicate restrictions
 * @export
 * @interface Restriction
 */
export interface Restriction {
    /**
     * A credential definition ID
     * @type {string}
     * @memberof Restriction
     */
    credentialDefinitionId: any;
    /**
     * A schema ID
     * @type {string}
     * @memberof Restriction
     */
    schemaId?: any;
}
