/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RevocationRequirement
 */
export interface RevocationRequirement {
    /**
     * Date at which the credential should be valid
     * @type {Date}
     * @memberof RevocationRequirement
     */
    validAt?: any;
    /**
     * Defines if the credential should be valid at the current date
     * @type {boolean}
     * @memberof RevocationRequirement
     */
    validNow?: any;
}
