/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SchemaCreate
 */
export interface SchemaCreate {
    /**
     * Schema name
     * @type {string}
     * @memberof SchemaCreate
     */
    name: any;
    /**
     * Schema version
     * @type {string}
     * @memberof SchemaCreate
     */
    version: any;
    /**
     * List of schema attributes
     * @type {Array&lt;string&gt;}
     * @memberof SchemaCreate
     */
    attributesName: any;
}
