/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerificationTemplate
 */
export interface VerificationTemplate {
    /**
     * The verificationTemplate id
     * @type {number}
     * @memberof VerificationTemplate
     */
    id: any;
    /**
     * The verificationTemplate name
     * @type {string}
     * @memberof VerificationTemplate
     */
    name: any;
    /**
     * 
     * @type {VerificationTemplateContent}
     * @memberof VerificationTemplate
     */
    content: any;
}
