/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerifiableCredentialMultipleProof
 */
export interface VerifiableCredentialMultipleProof {
    /**
     * The JSON-LD context of the credential.
     * @type {Array&lt;string&gt;}
     * @memberof VerifiableCredentialMultipleProof
     */
    context: any;
    /**
     * The ID of the credential.
     * @type {string}
     * @memberof VerifiableCredentialMultipleProof
     */
    id?: any | null;
    /**
     * The JSON-LD type of the credential.
     * @type {Array&lt;string&gt;}
     * @memberof VerifiableCredentialMultipleProof
     */
    type: any;
    /**
     * A JSON-LD Verifiable com.sicpa.bridge.api.jsonld.domain.model.Credential Issuer.
     * @type {string}
     * @memberof VerifiableCredentialMultipleProof
     */
    issuer: any;
    /**
     * The issuanceDate
     * @type {string}
     * @memberof VerifiableCredentialMultipleProof
     */
    issuanceDate: any;
    /**
     * The expirationDate
     * @type {string}
     * @memberof VerifiableCredentialMultipleProof
     */
    expirationDate?: any | null;
    /**
     * The subject
     * @type {any}
     * @memberof VerifiableCredentialMultipleProof
     */
    credentialSubject: any;
    /**
     * 
     * @type {Array&lt;LinkedDataProof&gt;}
     * @memberof VerifiableCredentialMultipleProof
     */
    proof: any;
}
