/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerifiablePresentation
 */
export interface VerifiablePresentation {
    /**
     * The JSON-LD context of the presentation.
     * @type {Array&lt;string&gt;}
     * @memberof VerifiablePresentation
     */
    context: any;
    /**
     * The holder
     * @type {string}
     * @memberof VerifiablePresentation
     */
    holder: any;
    /**
     * The JSON-LD type of the presentation.
     * @type {string}
     * @memberof VerifiablePresentation
     */
    type: any;
    /**
     * 
     * @type {VerifiableCredential}
     * @memberof VerifiablePresentation
     */
    verifiableCredential: any;
    /**
     * 
     * @type {Array&lt;LinkedDataProof&gt;}
     * @memberof VerifiablePresentation
     */
    proof: any;
}
