/* tslint:disable */
/* eslint-disable */
/**
 * Sicpa Bridge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerificationTemplateContent
 */
export interface VerificationTemplateContent {
    /**
     * The requested attributes. In order for the verification to be successful, all requested attribute should be validated
     * @type {Array&lt;RequestedAttribute&gt;}
     * @memberof VerificationTemplateContent
     */
    requestedAttributes: any;
    /**
     * The requested predicates. In order for the verification to be successful, all requested predicates should be validated
     * @type {Array&lt;RequestedPredicate&gt;}
     * @memberof VerificationTemplateContent
     */
    requestedPredicates: any;
    /**
     * 
     * @type {RevocationRequirement}
     * @memberof VerificationTemplateContent
     */
    revocationRequirement?: any;
}
