server:
  servlet:
    context-path: /api


spring:
  jackson:
    default-property-inclusion: non_null


  datasource:
    url: jdbc:postgresql://localhost:5432/bridge?createDatabaseIfNotExist=true
    username: postgres
    password: password


  jpa:
    #    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update



    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  mvc:
#    converters:
#      preferred-json-mapper: gson

aca-py-client:
  url: http://essif.adaptivespace.io:8080

train:
  url: http://atvtrain3-env.eba-gewjbrmq.eu-central-1.elasticbeanstalk.com
  #url: https://essif.trust-scheme.de/atvtrain

eidas-bridge:
  url: https://api.vidchain.net
  certificatePassword: 1234

