swagger: '2.0'
info:
  description: |
    This is a sample TRAIN_ATV server.
  version: 1.0.0
  title: TRAIN_ATV_API
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: TRAIN_ATV
    description: Train Verification API
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /api/v1/ssi/:
    post:
      tags:
        - TRAIN_ATV
      summary: Verification result based on issuer & trust scheme pointers
      description: Returns a Verification result from TRAIN_ATV
      produces:
        - application/json
      parameters:
        - in: body
          description: Verify trust scheme.
          name: TrustParameters
          schema:
            $ref: '#/definitions/TRAIN_ATV_Request_Params'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/TRAIN_ATV_Result'
        400:
          description: Invalid Issuer_name or URI supplied
        404:
          description: Train_ATV not found

definitions:
  TRAIN_ATV_Request_Params:
    type: object
    required:
      - Issuer
      - Trust_Scheme_Pointer
    properties:
      Issuer:
        type: string
      Trust_Scheme_Pointer:
        type: string
  TRAIN_ATV_Result:
    type: object
    properties:
      VerificationStatus:
        type: string
        description: Result of API
        enum:
          - OK
          - FAILED
      VerificationResult:
        type: object
        properties:
          ReceivedTrustSchemePointer:
            type: string
          FindingCorrespondingTrustSchemeInitiated:
            type: string
            enum:
              - OK
              - FAILED
          FoundCorrespondingTrustScheme:
            type: string
          TrustListDiscoveryInitiated:
            type: string
            enum:
              - OK
              - FAILED
          TrustListFoundAndLoaded:
            type: string
          FoundIssuer:
            type: string
          VerifyIssuer:
            type: string
            enum:
              - OK
              - FAILED
          VerificationSuccessful:
            type: string
            enum:
              - OK
              - FAILED